In [1]:
# Importing standard libraries
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
# Importing items file
items = pd.read_csv('items.csv')

# Importing users file
users = pd.read_csv('users.csv')

# Importing ratings file
ratings = pd.read_csv('ratings.csv')

In [3]:
# Merge items (movies) dataframe with ratings dataframe on common column movie_id
movie_ratings = pd.merge(items, ratings, on='movie_id')

In [4]:
# Create number of ratings column per movie in ratings dataset
ratings_average = pd.DataFrame(movie_ratings.groupby('title')['rating'].mean())

In [5]:
ratings_average['number_of_ratings'] = movie_ratings.groupby('title')['rating'].count()

# 

In [6]:
# Create a pivot table to display every rating of each user (vertical) for each movie (horizontal)
user_movie_rating = movie_ratings.pivot_table(index='user_id', columns='title', values='rating')
user_movie_rating.head()

title    'Til There Was You (1997)  1-900 (1994)  101 Dalmatians (1996)  \
user_id                                                                   
1                              NaN           NaN                    2.0   
2                              NaN           NaN                    NaN   
3                              NaN           NaN                    NaN   
4                              NaN           NaN                    NaN   
5                              NaN           NaN                    2.0   

title    12 Angry Men (1957)  187 (1997)  2 Days in the Valley (1996)  \
user_id                                                                 
1                        5.0         NaN                          NaN   
2                        NaN         NaN                          NaN   
3                        NaN         2.0                          NaN   
4                        NaN         NaN                          NaN   
5                        NaN         NaN                          NaN   

title    20,000 Leagues Under the Sea (1954)  2001: A Space Odyssey (1968)  \
user_id                                                                      
1                                        3.0                           4.0   
2                                        NaN                           NaN   
3                                        NaN                           NaN   
4                                        NaN                           NaN   
5                                        NaN                           4.0   

title    3 Ninjas: High Noon At Mega Mountain (1998)  39 Steps, The (1935)  \
user_id                                                                      
1                                                NaN                   NaN   
2                                                1.0                   NaN   
3                                                NaN                   NaN   
4                                                NaN                   NaN   
5                                                NaN                   NaN   

title                   ...                  Yankee Zulu (1994)  \
user_id                 ...                                       
1                       ...                                 NaN   
2                       ...                                 NaN   
3                       ...                                 NaN   
4                       ...                                 NaN   
5                       ...                                 NaN   

title    Year of the Horse (1997)  You So Crazy (1994)  \
user_id                                                  
1                             NaN                  NaN   
2                             NaN                  NaN   
3                             NaN                  NaN   
4                             NaN                  NaN   
5                             NaN                  NaN   

title    Young Frankenstein (1974)  Young Guns (1988)  Young Guns II (1990)  \
user_id                                                                       
1                              5.0                3.0                   NaN   
2                              NaN                NaN                   NaN   
3                              NaN                NaN                   NaN   
4                              NaN                NaN                   NaN   
5                              4.0                NaN                   NaN   

title    Young Poisoner's Handbook, The (1995)  Zeus and Roxanne (1997)  \
user_id                                                                   
1                                          NaN                      NaN   
2                                          NaN                      NaN   
3                                          NaN                      NaN   
4                                          NaN                

In [7]:
class MF():

    # Initializing the user-movie rating matrix, no. of latent features, alpha and beta.
    def __init__(self, R, K, alpha, beta, iterations):
        self.R = R
        self.num_users, self.num_items = R.shape
        self.K = K
        self.alpha = alpha
        self.beta = beta
        self.iterations = iterations

    # Initializing user-feature and movie-feature matrix 
    def train(self):
        self.P = np.random.normal(scale=1./self.K, size=(self.num_users, self.K))
        self.Q = np.random.normal(scale=1./self.K, size=(self.num_items, self.K))

        # Initializing the bias terms
        self.b_u = np.zeros(self.num_users)
        self.b_i = np.zeros(self.num_items)
        self.b = np.mean(self.R[np.where(self.R != 0)])

        # List of training samples
        self.samples = [(i, j, self.R[i, j]) for i in range(self.num_users) for j in range(self.num_items) if self.R[i, j] > 0]

        # Stochastic gradient descent for given number of iterations
        training_process = []
        for i in range(self.iterations):
            np.random.shuffle(self.samples)
            self.sgd()
            mse = self.mse()
            training_process.append((i, mse))
            if (i+1) % 20 == 0:
                print("Iteration: %d ; error = %.4f" % (i+1, mse))

        return training_process

    # Computing total mean squared error
    def mse(self):
        xs, ys = self.R.nonzero()
        predicted = self.full_matrix()
        error = 0
        for x, y in zip(xs, ys):
            error += pow(self.R[x, y] - predicted[x, y], 2)
        return np.sqrt(error)

    # Stochastic gradient descent to get optimized P and Q matrix
    def sgd(self):
        for i, j, r in self.samples:
            prediction = self.get_rating(i, j)
            e = (r - prediction)

            self.b_u[i] += self.alpha * (e - self.beta * self.b_u[i])
            self.b_i[j] += self.alpha * (e - self.beta * self.b_i[j])

            self.P[i, :] += self.alpha * (e * self.Q[j, :] - self.beta * self.P[i,:])
            self.Q[j, :] += self.alpha * (e * self.P[i, :] - self.beta * self.Q[j,:])

    # Ratings for user i and moive j
    def get_rating(self, i, j):
        prediction = self.b + self.b_u[i] + self.b_i[j] + self.P[i, :].dot(self.Q[j, :].T)
        return prediction

    # Full user-movie rating matrix
    def full_matrix(self):
        return mf.b + mf.b_u[:,np.newaxis] + mf.b_i[np.newaxis:,] + mf.P.dot(mf.Q.T)


In [8]:
R = np.array(ratings.pivot(index = 'user_id', columns ='movie_id', values = 'rating').fillna(0))
R

array([[5., 3., 4., ..., 0., 0., 0.],
       [4., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 5., 0., ..., 0., 0., 0.]])

In [9]:
mf = MF(R, K=20, alpha=0.001, beta=0.01, iterations=100)
training_process = mf.train()
print()
print("P x Q:")
print(mf.full_matrix())
print()

Iteration: 20 ; error = 296.1570
Iteration: 40 ; error = 291.1265
Iteration: 60 ; error = 287.8354
Iteration: 80 ; error = 282.6471
Iteration: 100 ; error = 273.4756

P x Q:
[[3.89589651 3.2564661  3.08151576 ... 3.33513351 3.41104424 3.36196559]
 [3.89646349 3.39960981 3.18128391 ... 3.38495701 3.53065885 3.478633  ]
 [3.37441153 2.75737871 2.59454335 ... 2.8042136  2.90370261 2.85718554]
 ...
 [4.20203219 3.60798002 3.38916368 ... 3.64885675 3.76066938 3.73320128]
 [4.36308025 3.86525032 3.68156865 ... 3.76725714 3.94361042 3.86111327]
 [3.69892496 3.22847037 3.05129917 ... 3.25157082 3.36091839 3.28606014]]

